pipeline {
    agent any 

    tools {
        nodejs 'node-22'
    }

    stages{
        stage('npm version') {
            steps {
                sh 'node -v'
                sh 'npm -v'
            }
        }
    }
}