pipeline {
    agent any 

    stages{
        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Validate') {
            steps {
                sh 'terraform validate'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }

    post {
        failure {
            withCredentials([string(credentialsId: 'slack-webhook', variable: 'SLACK_URL')]) {
                sh """
                    curl -s -X POST -H 'Content-type: application/json' \
                    --data '{"text":":x: *Pipeline FAILED!*\\n*Job:* ${env.JOB_NAME}\\n*Build #:* ${env.BUILD_NUMBER}\\n*Branch:* ${env.GIT_BRANCH}\\n*Details:* ${env.BUILD_URL}"}' \
                    \$SLACK_URL
                """
            }
        }
        unstable {
            withCredentials([string(credentialsId: 'slack-webhook', variable: 'SLACK_URL')]) {
                sh """
                    curl -s -X POST -H 'Content-type: application/json' \
                    --data '{"text":":warning: *Pipeline UNSTABLE!*\\n*Security issues found*\\n*Job:* ${env.JOB_NAME}\\n*Build #:* ${env.BUILD_NUMBER}\\n*Branch:* ${env.GIT_BRANCH}\\n*Details:* ${env.BUILD_URL}"}' \
                    \$SLACK_URL
                """
            }
        }
        success {
            withCredentials([string(credentialsId: 'slack-webhook', variable: 'SLACK_URL')]) {
                sh """
                    curl -s -X POST -H 'Content-type: application/json' \
                    --data '{"text":":white_check_mark: *Pipeline PASSED!*\\n*Job:* ${env.JOB_NAME}\\n*Build #:* ${env.BUILD_NUMBER}\\n*Branch:* ${env.GIT_BRANCH}"}' \
                    \$SLACK_URL
                """
            }
        }
    }
}